### ISSUE TITLE
Please Add Javascript Syntax Highlighting 

### ISSUE THREAD

**Issue by Nocturnal-Compiler** [jflepp/JFlepp.VS.Theme.DarkYellow#12]
This Theme has Very Good C# Syntax Highlighting I Hope You can Do  The Same With Js As Visual Studio 2022 Has Very Less Highlighting This Would Be A Addition Worth Adding.

**Comment by fl3pp** [comment]
Hi @Pro-Gamer-711-YT

The highlighting options in C# come from the abilities of the Roslyn platform to figure out elements like classes, enums, etc. based on the _semantic_ model. That is information from the compilation beyond just syntax.

Unfortunately, VS doesn't support semantic highlighting in JS. As far as I know, this isn't even possible for any editor, since semantic information is not available until _runtime_. This is just a result of JavaScript's interpreted and dynamically typed nature.

Maybe there are ways to overcome these limitations, but they certainly are not built-in inside VS nor VS Code. Making this possible is certainly beyond a color scheme which basically is just a color map.

Thus, I will be closing this issue. But I still want to thank you for making me aware that there are JS users in VS using this theme.

Best Regards
