### ISSUE TITLE
VS Code theme

### ISSUE THREAD

**Issue by davidhenley** [jflepp/JFlepp.VS.Theme.DarkYellow#4]
Could you create the VS Code theme as well?

**Comment by fl3pp** [comment]
I'm not using VSCode, so I don't think so. If you create one I'd happily link it from here.

As far as I know, it wouldn't even be possible to create such a Theme for VSCode, because it relies heavily on Visual Studios semantic coloring while VSCode only supports syntax coloring (not a 100% sure about that).
